name: anarise
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  dropdown_search: 5.0.6
  flip_card: ^0.7.0
  flutter:
    sdk: flutter
  flutter_inappwebview: ^5.7.2+3
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: 2.2.19
  get: 4.6.5
  get_storage: ^2.1.1
  google_fonts: 4.0.4
  lottie : 2.3.0
  permission_handler : 10.2.0
  http: 0.13.5
  introduction_screen: ^3.1.8
  readmore: ^2.2.0

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
flutter_native_splash:
  color: "#ffffff"
  image: assets/img/logo.png
  android_12:
    image: assets/img/logo.png
    icon_background_color: "#ffffff"
    image_dark: assets/img/logo.png
    icon_background_color_dark: "#ffffff"
  android: true
  ios: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/img/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
